model_name: Fyuhei1989/minicompe-demo-20250729
model_parameters:
  add_special_tokens: true
  data_parallel_size: 1
  dtype: bfloat16
  generation_parameters:
    frequency_penalty: 0.0
    max_new_tokens: 1024
    min_new_tokens: 0
    min_p: 0.0
    presence_penalty: 0.0
    repetition_penalty: 1.0
    seed: 42
    stop_tokens: null
    temperature: 1.0
    top_k: 50
    top_p: 1.0
  gpu_memory_utilization: 0.9
  max_model_length: 2048
  model_name: deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B
  multichoice_continuations_start_space: true
  pairwise_tokenization: true
  pipeline_parallel_size: 1
  revision: main
  seed: 1
  subfolder: null
  swap_space: 4
  tensor_parallel_size: 1
  trust_remote_code: true
  use_chat_template: true
